[build]
  command = "npm run build"
  publish = "_site"

[dev]
  command = "npm start"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
